name: Java CI
on: [push]
jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'  
      - uses: jenkinsci/jfr-setup-action@master
        with:
          jenkins-version: 2.489
          jenkins-pm-version: 2.13.2
          jfr-version: 1.0-beta-32
      - uses: jenkinsci/jfr-plugin-installation-action@master
        with:
          pluginstxt: plugins.txt
      - uses: jenkinsci/jfr-runtime-action@master
        with:
          command: run
          jenkinsfile: Jenkinsfile
          jcasc: jcasc.yml                               