name: Java CI
on: [push]
jobs:
  jenkins-container-pipeline:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jenkinsci/jenkinsfile-runner:latest
    steps:
      - uses: actions/checkout@v4
      - uses: jenkinsci/jfr-setup-action@master
      - uses:
          jenkinsci/jfr-container-action@master
      - uses: jenkinsci/jfr-plugin-installation-action@master
        with:
          pluginstxt: plugins.txt
      - uses: jenkinsci/jfr-runtime-action@master
        with:
          command: run
          jenkinsfile: Jenkinsfile
          jcasc: jcasc.yml
          initHook: groovy.init.d
