name: Java CI
on: [push]
jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: blaffitte-experiments/jfr-setup-action@master
        with:
          jenkins-version: 2.487
          jenkins-pm-version: 2.13.2
          jfr-version: 1.0-beta-32
      - uses: jenkinsci/jfr-plugin-installation-action@master
        with:
          pluginstxt: plugins.txt
      - uses: blaffitte-experiments/jfr-runtime-action@master
        with:
          command: run
          jenkinsfile: Jenkinsfile
          jcasc: jcasc.yml
          initHook: groovy.init.d                         